# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: aea1e110a02e7923d1bae9092cb9d5b97b4446e3e38df36f3c861bafdc966aef37101e40c781eafdf0baecd415de462f789b6dfe26fac9d87e652a0dc95c02ed

test:
  secret_key_base: af52f91414489d3888ad300dbe276f456856795f40f277f53101017267a7af4759203c92fbd14be6acc9a503f59de6e896dfcd32236f33a75cfe5be2928af46b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
